name = "netflix-clone"
compatibility_date = "2025-03-28"

# Define the correct entry point
main = "./build/index.js"

# Static site settings for Pages
[site]
bucket = "./build"

# ✅ Required for Cloudflare Pages deployment
build_output_dir = "./build"  # Changed this line
